# Generated by Django 5.1 on 2024-08-22 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='delete_added',
            new_name='date_added',
        ),
    ]
